28/08/21 (14:11:04) | ERROR: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
06/09/21 (15:52:01) | ERROR: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
09/09/21 (01:05:04) | ERROR: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
09/09/21 (11:54:52) | ERROR: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
09/09/21 (13:56:53) | ERROR: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
10/09/21 (15:25:36) | ERROR: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/fonsi/.config/bpytop/themes'
